# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c6736bd4-eee3-42bd-831c-b8dc47a8ab7c";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/home/weiwen" =
    { device = "/dev/disk/by-uuid/c6736bd4-eee3-42bd-831c-b8dc47a8ab7c";
      fsType = "btrfs";
      options = [ "subvol=home/weiwen" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/c6736bd4-eee3-42bd-831c-b8dc47a8ab7c";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/var/lib" =
    { device = "/dev/disk/by-uuid/c6736bd4-eee3-42bd-831c-b8dc47a8ab7c";
      fsType = "btrfs";
      options = [ "subvol=var/lib" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/c6736bd4-eee3-42bd-831c-b8dc47a8ab7c";
      fsType = "btrfs";
      options = [ "subvol=var/log" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9293-DBB2";
      fsType = "vfat";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
